### DISCUSSION TITLE
bundler: failed to load command: cap

### DISCUSSION THREAD

**Discussion by C10ne** [miloserdow/capistrano-deploy#86] [General]
Hi all,
I started getting above errors few days ago, so I'm just dropping by to leave a solution if someone runs into same issues.
I didn't dive deep to pinpoint what caused it, as I had big update to Laravel 11 to finish these days, and moved actions in that project to use Deployer, but ruby-setup update triggered the problems.

So, my yml had the following job:

```
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true
    - uses: miloserdow/capistrano-deploy@master
```

And I just tuned the versions to the ones that work:

```
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true
    - uses: miloserdow/capistrano-deploy@master
```

Hope no one will have the need for this, but, it doesn't cost a thing to post it. 😀
