### ISSUE TITLE
Ruby version mismatch

### ISSUE THREAD

**Issue by jrussellnj** [miloserdow/capistrano-deploy#2]
Hi! I'm really interested in using this deploy action, but I can't figure out how to get around this error:

```
Your Ruby version is 2.5.1, but your Gemfile specified 2.4.0
##[error]Error: The process 'sudo' failed with exit code 18
##[error]Node run failed with exit code 1
```

Is there a way to specify what Ruby version to use for the deploy?

**Comment by miloserdow** [comment]
Hi, I will work on that this week.

**Comment by seuros** [comment]
I think this action is doing too much. Setting the keys, Installing ruby and Capistrano should not be responsibility of this action.

I will try to open a PR later today with a stripped down version of action.

**Comment by JohnHexCarter** [comment]
Just came across as having an issue with this as well. Curious if there's development on this or if you could use some assistance.

**Comment by miloserdow** [comment]
Hi! It's in development, I was a little busy traveling and hopefully will it this weekends.

**Comment by miloserdow** [comment]
Hello! So there's a problem with installing RVM into ubuntu-latest which I was not able to solve easily.

I'm also starting to think that the right course of action if someone wants to use a custom ruby version, is to use this action (https://github.com/actions/setup-ruby) first. After this action, there should be a correct version installed though I haven't tested it myself.

**Comment by JohnHexCarter** [comment]
@miloserdow I just tried that and it still errored with the wrong Ruby version. Thanks, though.

**Comment by nrullo** [comment]
@miloserdow I've also tried but it doesn't fix the ruby version problem.

**Comment by miloserdow** [comment]
@JohnHexCarter @nrullo Can you try to use [setup-ruby](https://github.com/actions/setup-ruby) with the required version and then miloserdow/capistrano-deploy@no_install_ruby in your pipeline?

I created that branch with disabled _**apt-get install ruby full**_

**Comment by JohnHexCarter** [comment]
![code](https://user-images.githubusercontent.com/275490/72814999-fb93fd80-3c33-11ea-880e-0c0653445921.png)

Yeah, still not working. I don't think it's recognizing Ruby. Here's my full code (in case I'm doing something wrong):

```
name: deploy_production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.0

    - name: Deploy
      uses: miloserdow/capistrano-deploy@no_install_ruby
      with:
        target: 'production'
        deploy_key: ${{ secrets.DEPLOY_ENC_KEY }}

```
