### ISSUE TITLE
working-directory not operational

### ISSUE THREAD

**Issue by sulmanweb** [miloserdow/capistrano-deploy#7]
I have rails code in `api` folder. 
```yml
- uses: miloserdow/capistrano-deploy@v2
        with:
          working-directory: ./api
          target: staging
          deploy_key: ${{ secrets.DEPLOY_ENC_KEY }}
```
Error coming is:
```
Could not locate Gemfile
##[error]Error: The process 'bundle' failed with exit code 10
```

**Comment by felipecsl** [comment]
try using `api` instead of `./api`?

**Comment by ksz2k** [comment]
I have the same issue, for both variants: `./api` and `api`

```
    - uses: miloserdow/capistrano-deploy@v2
      with:
        target: staging
        working-directory: api
        ...
```

```
***[warning]Unexpected input 'working-directory', valid inputs are ['target', 'deploy_key', 'enc_rsa_key_pth']
>up]Run miloserdow/capistrano-deploy@v2
  with:
    target: staging
    working-directory: api
    deploy_key: ***
    enc_rsa_key_pth: config/deploy_id_rsa_enc
gem install bundler:1.17.3 --no-document
Successfully installed bundler-1.17.3
1 gem installed
bundle install --deployment --jobs=4 --without=production test
Could not locate Gemfile
```
